---
detect_level_crossing:
  ros__parameters:
    detect.level.red.hue_l: 0
    detect.level.red.hue_h: 26
    detect.level.red.saturation_l: 17
    detect.level.red.saturation_h: 255
    detect.level.red.lightness_l: 80
    detect.level.red.lightness_h: 255
